In [1]:
import numpy as np

In [7]:
def sliding_window_preprocessing(sequence, history_window, horizon=1):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + history_window
        # check if we are beyond the sequence
        if end_ix + horizon > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix:end_ix+horizon]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X), np.array(y)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
X, y = sliding_window_preprocessing(arr, 3, 6)
for i in range(len(X)):
    print(X[i], y[i])

[1 2 3] [4 5 6 7 8 9]
[2 3 4] [ 5  6  7  8  9 10]
[3 4 5] [ 6  7  8  9 10 11]
[4 5 6] [ 7  8  9 10 11 12]
[5 6 7] [ 8  9 10 11 12 13]
[6 7 8] [ 9 10 11 12 13 14]


In [2]:
def feature_scaling(sequence, method):
    pass

def reverse_scaling(sequence):
    pass

In [ ]:
def sliding_window_with_breakdown(sequence, history_window, horizon, breakdown_indices):
    pass